name: 📅 Add New Calendar Event
description: Add an event to the SCRF calendar
title: "📅 - New Event"
labels: []
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new user form!

  - type: input
    id: title
    attributes:
      label: ◾Title◾      
      placeholder: Name of Event
    validations:
#      required: true      
  
  - type: input
    id: start-time
    attributes:
      label: Start Time◾
      description: Pacific Standard Time (PST/PDT)
    validations:
#      required: true

  - type: input
    id: cadence
    attributes:
      label: Cadence
      description: How often does this meeting occur? 
      placeholder: First Monday of the month. Once a month. Etc.
    validations:
#      required: true

  - type: input
    id: duration
    attributes:
      label: Duration
      description: How long is this event?      
    validations:
#      required: true      

  - type: input
    id: location
    attributes:
      label: Location
      description: What is the URL of the meeting space?

  - type: textarea
    id: description
    attributes:
      label: ◾Description◾