name: 📅 Add New Event
about: Add an event to the SCRF calendar
description: Add an event to the SCRF calendar
title: "📅 - New Event"
labels: []
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new user form!

  - type: textarea
    id: text
    attributes:
      label: Issue Text
      description: text goes here!