name: New Issue to Project Board

on:
  issues:
    types: [opened]

jobs:
  add-to-calendar:    
    runs-on: ubuntu-latest
    if: contains( github.event.issue.title, '📅')
    steps:    
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/smartcontractresearchforum/projects/30
          github-token: ${{ secrets.DISCOVERY_ISSUE_PB_PAT }}         